export const MANUFACTURING_WALKTHROUGH = {
  reviewed: "2026-09-06",
  disclosure: "A fictional 18-plant manufacturer across the UK and Europe. These are illustrative requirements and supplier answers, not a live project or a customer result.",
  steps: [
    { title: "Describe the business need", text: "We need resilient connectivity across 18 plants, separation between office IT and production OT, controlled supplier maintenance access and migration within approved shutdown windows." },
    { title: "Review the requirements and gaps", text: "Record site locations, business-critical applications, the operating model and migration constraints. Confirm missing bandwidths, outage tolerances, local contacts and remote-user numbers before treating them as requirements. Suggestions remain unconfirmed until the buyer accepts them." },
    { title: "Choose the document depth and add bespoke questions", text: "Use a short brief or Short RFP for core needs, or a Detailed RFP for all eight sections. A bespoke question could be: How will you maintain access to our legacy production application during a WAN failover without bypassing the IT/OT boundary? Request a proposed test and evidence, rather than accepting a yes/no answer." },
    { title: "Review the anonymous notice", text: "Example notice: A manufacturer seeks resilient SD-WAN across 18 UK and European plants, with IT/OT separation, controlled maintenance access and phased migration. Exact site addresses, company identity and contacts stay private. The buyer reviews the notice and verifies a work email before publishing." },
    { title: "Evaluate the responses", text: "After publication, review actual supplier responses and pricing privately as they arrive. Compare evidence against the same requirements and follow up on omissions. For connectivity, Netify sources offers and emails the buyer when a quote is added to Market responses. Neither publication nor an AI recommendation guarantees a supplier response or places an order." },
  ],
  responses: [
    { requirement: "Production continuity", a: "Proposes a failover test during a scheduled maintenance window.", b: "States high availability but does not supply a test plan.", followup: "Request measurable failover criteria and a rollback plan from both." },
    { requirement: "IT/OT separation", a: "Provides an outline policy boundary; legacy protocol testing remains open.", b: "Offers segmentation but leaves remote contractor access unclear.", followup: "Ask each supplier to evidence the plant-specific access policy and exception handling." },
    { requirement: "Comparable commercial terms", a: "Separates recurring and installation charges; licence scope needs clarification.", b: "Provides a bundled scope without an installation breakdown.", followup: "Request the same term, currency, inclusions, exclusions and price-validity basis." },
  ],
} as const;

export const MARKETPLACE_EXAMPLE_VERSION = "marketplace-example/1.0.0" as const;
export const MARKETPLACE_EXAMPLES = {
  "retail-quick-opportunity": { type: "quick_list", title: "Anonymous retail SASE opportunity example", sector: "Retail and e-commerce", summary: "A synthetic 80-site retailer replaces an expiring MPLS estate, separates payment and guest traffic, and needs resilient managed SASE within nine months.", inputs: ["80 UK and Ireland sites", "Managed operating model", "PCI DSS payment boundary", "Cellular trading continuity", "Nine-month target"], outputs: ["Anonymous Opportunity Board summary", "Aggregate match coverage before publication", "Provider identities only after MarketUnlock"], limitations: ["The organisation is fictional.", "PCI DSS scope requires buyer and assessor confirmation."] },
  "healthcare-sector-project": { type: "sector", title: "Healthcare SASE project example", sector: "Healthcare", summary: "A synthetic healthcare group evaluates clinical resilience, patient-data controls, DSPT applicability, monitored devices and staff/guest separation before confirming requirements.", inputs: ["12 clinical sites", "Clinical and administrative traffic", "DSPT applicability unconfirmed", "Monitored-device dependencies"], outputs: ["Unconfirmed governed sector recommendations", "Gap questions and buyer decisions", "Sector-aware RFP or opportunity"], limitations: ["No real patient or organisation data is used.", "Clinical-safety duties require competent human review."] },
  "manufacturing-rfp": { walkthrough: MANUFACTURING_WALKTHROUGH, type: "rfp", title: "Manufacturing SD-WAN RFP example", sector: "Manufacturing", summary: "A synthetic manufacturer develops a detailed SD-WAN RFP for 18 plants with explicit IT/OT separation, brownfield compatibility, remote-maintenance control and constrained cutover windows.", inputs: ["18 UK and European plants", "Existing MPLS and industrial protocols", "Co-managed operations", "Fixed maintenance windows"], outputs: ["Governed RFP sections", "Comparable supplier evidence questions", "Anonymous board projection"], limitations: ["OT protocol support remains a supplier validation item.", "Safety impacts require site-specific engineering review."] },
  "financial-services-comparison": { type: "comparison", title: "Financial-services provider comparison example", sector: "Financial services", summary: "A synthetic regulated buyer compares technology vendors and managed providers using operational resilience, auditability, third-party diligence, concentration risk and exit planning.", inputs: ["UK and European delivery", "Operational-resilience impact tolerances", "Evidence retention", "Provider exit obligations"], outputs: ["Aggregate pre-publication coverage", "Post-publication ranked provider reasons", "Unresolved evidence shown separately"], limitations: ["Regulatory applicability is not legal advice.", "Stale or unknown evidence cannot score as confirmed support."] },
} as const;
export type MarketplaceExampleSlug = keyof typeof MARKETPLACE_EXAMPLES;
