import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { MARKETPLACE_EXAMPLES, MARKETPLACE_EXAMPLE_VERSION, type MarketplaceExampleSlug } from "@/lib/marketplace-examples";
import { PROVIDER_MATCH_METHODOLOGY_VERSION } from "@/lib/provider-matching";
import { PUBLICATION_POLICY_VERSION } from "@/lib/publication-policy";

export function generateStaticParams() { return Object.keys(MARKETPLACE_EXAMPLES).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const example = MARKETPLACE_EXAMPLES[slug as MarketplaceExampleSlug]; return example ? { title: example.title, description: example.summary, alternates: { canonical: `https://netify.co.uk/sase/examples/${slug}/`, types: { "application/json": `https://netify.co.uk/sase/examples/${slug}/data.json` } } } : { title: "Example not found" }; }

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const example = MARKETPLACE_EXAMPLES[slug as MarketplaceExampleSlug]; if (!example) notFound();
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: example.title, description: example.summary, isAccessibleForFree: true, publisher: { "@id": "https://netify.co.uk/#organization" }, mainEntityOfPage: `https://netify.co.uk/sase/examples/${slug}/` };
  return <main className="mx-auto max-w-4xl px-6 py-16"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><p className="eyebrow">Permanent synthetic example · {example.type.replaceAll("_", " ")}</p><h1 className="mt-3 text-4xl font-semibold">{example.title}</h1><p className="mt-5 text-lg leading-8 text-[var(--ink-700)]">{example.summary}</p><div className="mt-10 grid gap-8 md:grid-cols-2"><section><h2 className="text-xl font-semibold">Inputs</h2><ul className="mt-3 list-disc space-y-2 pl-5">{example.inputs.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h2 className="text-xl font-semibold">Outputs</h2><ul className="mt-3 list-disc space-y-2 pl-5">{example.outputs.map((item) => <li key={item}>{item}</li>)}</ul></section></div><section className="mt-10 rounded-lg border border-amber-200 bg-amber-50 p-5"><h2 className="text-xl font-semibold">Limitations</h2><ul className="mt-3 list-disc space-y-2 pl-5">{example.limitations.map((item) => <li key={item}>{item}</li>)}</ul></section><p className="mt-8 text-sm text-[var(--ink-500)]">Example {MARKETPLACE_EXAMPLE_VERSION} · matching {PROVIDER_MATCH_METHODOLOGY_VERSION} · publication {PUBLICATION_POLICY_VERSION}. This is not a live buyer project and contains no private data.</p><a href={`/sase-sd-wan-rfp-builder/?journey=${example.type === "rfp" ? "build_rfp" : example.type === "quick_list" ? "quick_list" : "find_providers"}`} className="mt-6 inline-flex rounded-full bg-amber-500 px-6 py-3 font-semibold text-zinc-950">Start your own private project</a></main>;
}
