/**
 * Netify Security Sourcing: verdict → RFP adapter (Phase B step 3).
 *
 * ADAPTER ONLY. This module converts a SecurityScopeVerdict into the
 * EXISTING RfpSection[]/RfpQuestion shapes and nothing else: no new
 * document model, no editor, no publish flow. The output is written into
 * ProjectDetails.rfp_sections and from that moment the existing RFP
 * Builder, preview, download, publication and response machinery own it.
 *
 * Informational content (scope statement, exclusions with reasons, the
 * against-interest record, provenance) travels as priority "optional"
 * items: the platform's existing non-response tier. Proven inert:
 * RfpResponder renders optional as read-only information (never an
 * input), bid-review counts only required/mandatory questions, and
 * rfp-evaluation's activeQs excludes optional from every score.
 *
 * Deterministic (Article 3): same verdict, same sections, always. No
 * clock, no randomness; provenance uses the verdict's own generatedAt.
 *
 * The transparency guard lives here too, beside the generator, sharing
 * protectedTransparencyItems() so guard and generator cannot drift. It is
 * NARROW (Robert's condition 2): it checks only the protected item ids
 * and their verbatim text against the STORED verdict; every ordinary
 * question, weight, flag and section stays freely editable.
 */

import type { ProjectDetails, RfpQuestion, RfpSection } from "@/lib/rfp-types";
import type { CapabilityId, SecurityScopeVerdict } from "@/lib/security/rulebook";
import { bankSectionsFor, BANK_VERSION, type CapabilityNeed } from "@/lib/security/criteria";

export const TRANSPARENCY_CATEGORY = "Scoping and exclusions";

export const CAPABILITY_LABELS: Record<CapabilityId, string> = {
  endpoint: "Endpoint protection",
  mdr_soc: "Managed detection and response (MDR/SOC)",
  sse: "Security Service Edge (SSE)",
  siem_logging: "SIEM and log management",
  managed_firewall: "Managed firewall",
  awareness: "Security awareness training",
  email_security: "Email security",
  backup_resilience: "Backup and resilience",
};

const label = (id: CapabilityId) => CAPABILITY_LABELS[id] ?? id;

/** An informational line in the existing question shape: the platform's
 *  own non-response tier. Never an input, never counted, never scored.
 *  supplierLens (D0): the same constitutional truth phrased for the
 *  audience that quotes. The respond view prefers it and falls back to
 *  text, so blanking it simply shows the audit wording: tampering with
 *  the projection achieves nothing. text stays the protected field. */
function statement(id: string, text: string, rationale: string, supplierLens = ""): RfpQuestion {
  return {
    id,
    feature_id: "custom",
    text,
    evidence_requested: "",
    rationale,
    priority: "optional",
    source: "custom",
    buyer_lens: "",
    supplier_lens: supplierLens,
    mandatory: false,
    weight: 1,
  };
}

/**
 * The constitutionally protected items (Articles 2, 6 and 9): the
 * against-interest record, the exclusions with their reasons, and the
 * provenance line. Pure function of the verdict, used by BOTH the
 * generator and the write-gate guard, so what is protected is exactly
 * what was generated. Everything else in the document is the buyer's.
 */
export function protectedTransparencyItems(v: SecurityScopeVerdict): Array<{ id: string; text: string }> {
  const items: Array<{ id: string; text: string }> = [];
  for (const e of v.againstInterest) {
    items.push({
      id: `tr_ai_${e.capabilityId}`,
      text: `Recorded against Netify's commercial interest: ${e.statement}`,
    });
  }
  for (const n of v.summary.not_recommended) {
    items.push({
      id: `tr_excl_${n.capabilityId}`,
      text: `Excluded from scope: ${label(n.capabilityId)}. Reason: ${n.reason}${n.alternative ? ` Alternative: ${n.alternative}` : ""}`,
    });
  }
  items.push({
    id: "tr_versions",
    text: `Generated by Netify Security Sourcing under ${v.rulebookVersion}, question bank v${BANK_VERSION}, from verdict ${v.inputDigest} at ${v.generatedAt}. The against-interest and exclusion records above, and this provenance line, cannot be removed or reworded; annotate alongside them instead.`,
  });
  return items;
}

/** Generate the document sections from a verdict. Pure and deterministic. */
export function generateRfpSections(v: SecurityScopeVerdict): RfpSection[] {
  const required = v.capabilities.filter((c) => c.needed === "required");
  const recommended = v.capabilities.filter((c) => c.needed === "recommended");

  const info: RfpQuestion[] = [];

  const scopeParts: string[] = [];
  scopeParts.push(
    required.length
      ? `In scope (required): ${required.map((c) => label(c.id)).join("; ")}.`
      : "No capability was assessed as strictly required; see the conditional items below.",
  );
  if (recommended.length) scopeParts.push(`Conditional (recommended, subject to the buyer's confirmation): ${recommended.map((c) => label(c.id)).join("; ")}.`);
  if (v.serviceModel) scopeParts.push(`Service model: ${v.serviceModel.replace(/_/g, " ")}.`);
  if (v.pathRecommendation) scopeParts.push(`Recommended route: ${v.pathRecommendation.replace(/_/g, " ")}.`);
  info.push(statement("tr_scope", scopeParts.join(" "), `Scope derived from the ${v.rulebookVersion} verdict; rules: ${[...new Set(v.capabilities.flatMap((c) => c.firedRules))].join(", ") || "none"}.`));

  for (const c of recommended) {
    info.push(statement(
      `tr_cond_${c.id}`,
      `Conditional capability: ${label(c.id)}. ${c.reasoning}`,
      `Recommended (not required) under ${v.rulebookVersion}; rules: ${c.firedRules.join(", ") || "none"}. The buyer decides whether to keep this in scope.`,
      `Conditional: if ${label(c.id)} questions appear in this document, respond to them; the buyer decided to keep this capability in scope.`,
    ));
  }

  const protectedItems = protectedTransparencyItems(v);
  for (const p of protectedItems) {
    const isVersions = p.id === "tr_versions";
    const isAi = p.id.startsWith("tr_ai_");
    const cap = isAi ? v.capabilities.find((c) => `tr_ai_${c.id}` === p.id) : undefined;
    // Supplier lens (D0): composed deterministically from the same verdict.
    let lens = "";
    if (isVersions) {
      lens = "This RFP was generated under a versioned methodology; respond to the questions as asked.";
    } else if (isAi) {
      const e = v.againstInterest.find((x) => `tr_ai_${x.capabilityId}` === p.id);
      const capLabel = e ? label(e.capabilityId) : "This capability";
      lens = `No ${capLabel.toLowerCase()} response is requested in this RFP.${e?.evidence ? ` Existing provision: ${e.evidence}.` : ""}`;
    } else {
      const n = v.summary.not_recommended.find((x) => `tr_excl_${x.capabilityId}` === p.id);
      const capLabel = n ? label(n.capabilityId) : "This capability";
      lens = `${capLabel} is excluded from this RFP. Do not include it in your response or pricing.`;
    }
    info.push(statement(
      p.id,
      p.text,
      isVersions
        ? "Provenance (Article 3): the verdict digest makes this document independently checkable."
        : isAi
          ? `Against-interest record (Article 14): the rulebook routed away from a Netify-monetised option${cap ? `; rules: ${cap.firedRules.join(", ")}` : ""}.`
          : `Exclusion with reason (Article 6): recorded so suppliers do not quote for it and the buyer knows why.`,
      lens,
    ));
  }

  if (v.gaps.length) {
    info.push(statement(
      "tr_gaps",
      `Open scoping gaps: ${v.gaps.map((g) => g.question).join(" ")} This draft may proceed, but publication requires each gap to be answered (re-scope) or individually accepted by the buyer.`,
      "Gap handling (acceptance check 7): drafts tolerate gaps; publication does not.",
      "Some scoping details were accepted as open by the buyer. Answer the questions as asked and state your assumptions where relevant.",
    ));
  }

  const caps: CapabilityNeed[] = v.capabilities
    .filter((c) => c.needed === "required" || c.needed === "recommended")
    .map((c) => ({ id: c.id, needed: c.needed as "required" | "recommended" }));
  const servicePath =
    v.pathRecommendation === "service_path" ||
    v.pathRecommendation === "hybrid" ||
    v.serviceModel === "fully_managed" ||
    v.serviceModel === "co_managed";

  return [
    { category: TRANSPARENCY_CATEGORY, included: true, questions: info },
    ...bankSectionsFor(caps, servicePath),
  ];
}

/* ------------------------------------------------------------------ */
/* Write-gate guard (Robert's condition 2: narrow, loud, recoverable)  */
/* ------------------------------------------------------------------ */

export class ProtectedContentError extends Error {}

/**
 * Refuse a save that removes or rewords protected transparency content,
 * or that shrinks the engine Record. Called from saveProject (the single
 * write path) for security engine records only.
 *
 * NARROW by design: compares protected item ids and text against the
 * verdict already STORED on the record (never the incoming payload), so
 * a client cannot talk the guard out of anything, and ordinary edits
 * (question wording, weights, mandatory flags, new sections, deletions
 * of unprotected items) pass untouched. The thrown message names each
 * missing item so the buyer can restore it without losing other work;
 * the builder keeps unsaved edits on screen (saves are optimistic).
 */
export function assertEngineArtefactsIntact(existing: ProjectDetails, next: ProjectDetails): void {
  if (existing.engine !== "security_sourcing") return;

  // The Record is append-only (Article 9): verdicts and artefact
  // snapshots may grow, never shrink or mutate.
  const exV = existing.engine_data?.verdicts ?? [];
  const nxV = next.engine_data?.verdicts ?? [];
  if (nxV.length < exV.length) {
    throw new ProtectedContentError("The verdict record is append-only and cannot be shortened. Re-read the project (GET) and resubmit your edit on top of it.");
  }
  for (let i = 0; i < exV.length; i++) {
    if (nxV[i]?.version !== exV[i].version || nxV[i]?.input_digest !== exV[i].input_digest) {
      throw new ProtectedContentError("The verdict record is append-only and cannot be rewritten. Re-read the project (GET) and resubmit your edit on top of it.");
    }
  }
  const exA = existing.engine_data?.artefacts ?? [];
  const nxA = next.engine_data?.artefacts ?? [];
  if (nxA.length < exA.length) {
    throw new ProtectedContentError("Generated document versions are append-only and cannot be removed. Re-read the project (GET) and resubmit your edit on top of it.");
  }
  for (let i = 0; i < exA.length; i++) {
    if (nxA[i]?.version !== exA[i].version || nxA[i]?.input_digest !== exA[i].input_digest) {
      throw new ProtectedContentError("Generated document versions are append-only and cannot be rewritten. Re-read the project (GET) and resubmit your edit on top of it.");
    }
  }

  // Transparency items: only checked once a document has been generated.
  if (exA.length === 0) return;
  const stored = exV[exV.length - 1]?.verdict as SecurityScopeVerdict | undefined;
  if (!stored || !Array.isArray(stored.againstInterest)) return;

  const byId = new Map<string, { text: string; priority: string; sectionIncluded: boolean }>();
  for (const s of next.rfp_sections ?? []) {
    for (const q of s.questions) byId.set(q.id, { text: q.text, priority: q.priority, sectionIncluded: s.included });
  }
  const violations: string[] = [];
  for (const p of protectedTransparencyItems(stored)) {
    const found = byId.get(p.id);
    if (!found) violations.push(`"${p.text.slice(0, 70)}…" (${p.id}) was removed`);
    else if (found.text !== p.text) violations.push(`"${p.text.slice(0, 70)}…" (${p.id}) was reworded`);
    else if (!found.sectionIncluded) violations.push(`"${p.text.slice(0, 70)}…" (${p.id}) was hidden by excluding its section`);
  }
  if (violations.length) {
    throw new ProtectedContentError(
      `This save was refused because protected scoping transparency would be lost: ${violations.join("; ")}. ` +
      `Restore the listed items exactly as generated (your other edits are still in the editor and will save once restored). ` +
      `These records are constitutional (Articles 2, 6 and 14): annotate alongside them instead of editing them.`,
    );
  }
}
