import type { Metadata } from "next";
import Link from "next/link";
import { BEST_PAGES, type BestPage } from "@/lib/best-pages";
import { SITE_URL, getBreadcrumbSchema, getOrganizationSchema } from "@/lib/structured-data";

/**
 * Index page for the ranked "best of" shortlists. Previously /best/ was a
 * 404 (only the [slug] pages existed) — added 2026-07-02 per
 * menu-redesign-plan.md §6 as the natural parent for the sector, organisation
 * size and priority shortlists, and the target of the sidebar's
 * "Best by sector" link.
 */

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Best SD-WAN and SASE providers: ranked shortlists (2026)",
  description:
    "Ranked SD-WAN and SASE provider shortlists by sector, organisation size and project priority. Scored across 40 capability features by Netify. Vendor-neutral, reproducible methodology.",
  alternates: { canonical: `${SITE_URL}/best/` },
  openGraph: {
    title: "Best SD-WAN and SASE providers: ranked shortlists (2026)",
    description:
      "Ranked SD-WAN and SASE provider shortlists by sector, organisation size and project priority, scored across 40 capability features.",
    url: `${SITE_URL}/best/`,
    type: "website",
    locale: "en_GB",
  },
};

const groups: { title: string; intro: string; pages: BestPage[] }[] = [
  {
    title: "By sector",
    intro: "Providers with public evidence of sector capability, sector grade weighted double.",
    pages: BEST_PAGES.filter((p) => p.input.sector),
  },
  {
    title: "By organisation size",
    intro: "Providers positioned for your organisation scale, from small business to global enterprise.",
    pages: BEST_PAGES.filter((p) => p.input.organisation_size),
  },
  {
    title: "By project priority",
    intro: "Feature weighting tuned for the outcome your project is chasing.",
    pages: BEST_PAGES.filter((p) => p.input.intent),
  },
];

export default function BestIndexPage() {
  return (
    <div className="max-w-6xl mx-auto px-6 py-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(getOrganizationSchema()) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(getBreadcrumbSchema("Best SD-WAN and SASE providers", "/best/")),
        }}
      />

      <div className="mb-12 fade-rise">
        <p className="eyebrow mb-3">Ranked shortlists · Updated 2026</p>
        <h1 className="mb-4">Best SD-WAN and SASE providers</h1>
        <p className="text-lg text-[var(--ink-700)] max-w-3xl">
          Every shortlist below is generated by the same scoring engine that powers the interactive
          shortlist builder: 30 platforms and managed providers, graded across 40 capability
          features. Pick the lens that matches your situation, or refine any list interactively.
        </p>
        <div className="mt-5 flex gap-3 flex-wrap">
          <Link
            href="/shortlist"
            className="inline-flex items-center gap-2 px-4 py-2.5 bg-amber-500 text-zinc-950 font-medium no-underline hover:bg-amber-400 transition-colors rounded-full text-sm"
          >
            Build your own shortlist →
          </Link>
          <Link
            href="/vendors"
            className="inline-flex items-center gap-2 px-4 py-2.5 border border-[var(--ink-300,#d4d4d8)] text-[var(--ink-900)] font-medium no-underline hover:bg-[var(--ink-100,#f4f4f5)] transition-colors rounded-full text-sm"
          >
            Browse all vendors
          </Link>
        </div>
      </div>

      <div className="space-y-14">
        {groups.map((group) => (
          <section key={group.title}>
            <h2 className="mb-1.5">{group.title}</h2>
            <p className="text-[var(--ink-500)] mb-6">{group.intro}</p>
            <ul className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 list-none m-0 p-0">
              {group.pages.map((page) => (
                <li key={page.slug}>
                  <Link
                    href={`/best/${page.slug}`}
                    className="block h-full rounded-xl border border-[var(--ink-200)] bg-[var(--paper-card,#fff)] p-5 no-underline transition-colors hover:border-[var(--ink-300,#d4d4d8)]"
                  >
                    <p className="font-medium text-[var(--ink-900)] leading-snug mb-2">{page.title}</p>
                    <p className="text-sm text-[var(--ink-500)] leading-snug">{page.metaDescription}</p>
                  </Link>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </div>
    </div>
  );
}
