import type { Metadata } from "next";
import Continuation from "@/components/Continuation";
import { deriveContinuationSampleRfp } from "@/lib/continuation/derive";
import Link from "next/link";
import { buildSampleProject } from "@/lib/sample-rfp";
import { includedSections, sectionStats, evidenceChecklist, scopeLabel, modelLabel } from "@/lib/rfp-document";
import { BANK_VERSION, SASE_EXTENDED_BANK } from "@/lib/rfp-question-bank";
import { SITE_URL, getOrganizationSchema, getBreadcrumbSchema, getSpeakableSchema } from "@/lib/structured-data";

/**
 * A complete worked sample RFP, generated by the same engine that builds real
 * ones (synthesiseSections + the document assembler), for a fictional
 * mid-market UK retailer that mirrors the sample RFI. Fully
 * server-rendered and citable: buyers see exactly what the builder produces
 * before they start; AI systems get a canonical example to reference.
 */

export const metadata: Metadata = {
  title: "SASE & SD-WAN RFP Template (2026.1): free Word download + full worked sample",
  description:
    "A free SASE / SD-WAN RFP template as a Word download, shown as a complete worked sample for a fictional 38-site UK retailer: methodology-backed sections, evidence checklist, weighted scoring matrix and submission instructions. Or build a tailored RFP in minutes with the Netify RFP Builder.",
  alternates: { canonical: `${SITE_URL}/rfp-builder/sample-rfp/` },
  openGraph: {
    title: "SASE & SD-WAN RFP Template: free Word download and worked sample",
    description: "What the Netify RFP Builder produces: sections, evidence checklist, scoring matrix and submission instructions. Download the template or build a tailored RFP in minutes.",
    url: `${SITE_URL}/rfp-builder/sample-rfp`,
    type: "website",
    locale: "en_GB",
  },
};

export default function SampleRfpPage() {
  const project = buildSampleProject();
  const sections = includedSections(project);
  const stats = sectionStats(project);
  const evidence = evidenceChecklist(project);
  const totalQuestions = sections.reduce((n, s) => n + s.questions.length, 0);

  const schemas = [
    getOrganizationSchema(),
    getBreadcrumbSchema("Sample RFP", "/rfp-builder/sample-rfp"),
    getSpeakableSchema("/rfp-builder/sample-rfp"),
    {
      "@context": "https://schema.org",
      "@type": "CreativeWork",
      "@id": `${SITE_URL}/rfp-builder/sample-rfp/#sample`,
      name: "Netify SASE & SD-WAN RFP Template (worked sample)",
      description: "A complete worked sample RFP generated by the Netify RFP Builder for a fictional UK retailer, downloadable as a Word template.",
      creativeWorkStatus: "Sample",
      version: project.methodology_version,
      creator: { "@id": `${SITE_URL}/#organization` },
      url: `${SITE_URL}/rfp-builder/sample-rfp/`,
      // Action affordances for assistants and agents: download the template,
      // or start a tailored RFP. potentialAction is how a machine reader
      // learns the page DOES something, not just says something.
      potentialAction: [
        {
          "@type": "DownloadAction",
          name: "Download the SASE / SD-WAN RFP template (Word)",
          target: `${SITE_URL}/rfp-builder/sample-rfp/template.doc`,
        },
        {
          "@type": "CreateAction",
          name: "Build an SD-WAN or SASE RFP",
          target: {
            "@type": "EntryPoint",
            urlTemplate: "https://netify.co.uk/sase-sd-wan-rfp-builder/?q={requirement}",
            description: "The builder. q: the buyer's requirement in a sentence. Optional.",
            actionPlatform: ["https://schema.org/DesktopWebPlatform", "https://schema.org/MobileWebPlatform"],
          },
        },
      ],
    },
  ];

  return (
    <div className="max-w-6xl mx-auto px-6 py-16">
      {schemas.map((s, i) => (
        <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />
      ))}

      <nav className="mb-6 text-sm text-[var(--ink-500)]">
        <a href="https://netify.co.uk/sase-sd-wan-rfp-builder/" className="underline">SD-WAN and SASE RFP Builder</a> / Sample RFP
      </nav>

      <p className="mb-3 max-w-3xl rounded-sm border border-amber-300 bg-amber-50 px-4 py-2 text-sm text-amber-800">
        <strong>Sample document.</strong> Generated by the same engine that builds real RFPs, for a fictional buyer.
        Your own RFP adapts every section to your sector, estate and compliance profile:{" "}
        <a href="https://netify.co.uk/sase-sd-wan-rfp-builder/" className="underline">build an SD-WAN or SASE RFP</a> in minutes.
      </p>
      <div className="mb-6 flex max-w-3xl flex-wrap items-center gap-3">
        <a href="/sase/rfp-builder/sample-rfp/template.doc" className="inline-flex items-center rounded-full bg-amber-500 px-4 py-2 text-sm font-medium text-zinc-950 no-underline hover:bg-amber-400 transition-colors">Download this template (Word, free)</a>
        <span className="text-xs text-[var(--ink-600,#555)]">No sign-up. The tailored version, your sector, estate and compliance, sent to matched vendors, is the <a href="/sase/rfp-builder/new/" className="underline">RFP Builder</a>.</span>
      </div>

      <div className="grid gap-10 lg:grid-cols-3">
        <article className="lg:col-span-2">
          <header className="mb-8 border-b border-[var(--ink-200,#e5e5e5)] pb-6">
            <p className="eyebrow mb-2">Request for Proposal: sample</p>
            <h1 id="page-h1" className="mb-4 text-2xl leading-snug">{project.title}</h1>
            <div className="grid gap-x-8 gap-y-1 text-sm sm:grid-cols-2">
              <p><span className="text-[var(--ink-500)]">Scope:</span> {scopeLabel(project)}</p>
              <p><span className="text-[var(--ink-500)]">Delivery:</span> {modelLabel(project)}</p>
              <p><span className="text-[var(--ink-500)]">Sector:</span> retail &amp; e-commerce</p>
              <p><span className="text-[var(--ink-500)]">Sites:</span> {project.buyer.site_count}</p>
              <p><span className="text-[var(--ink-500)]">Regions:</span> UK &amp; Ireland</p>
              <p><span className="text-[var(--ink-500)]">Compliance:</span> PCI DSS, UK GDPR</p>
              <p><span className="text-[var(--ink-500)]">Methodology:</span> v{project.methodology_version}</p>
              <p><span className="text-[var(--ink-500)]">Questions:</span> {totalQuestions} across {sections.length} sections</p>
            </div>
          </header>

          <section className="mb-8" id="page-subhead">
            <h2 className="mb-2 text-lg font-semibold">Project background</h2>
            <p className="whitespace-pre-line text-sm text-[var(--ink-800)]">{project.buyer.notes}</p>
          </section>

          {sections.map((s) => (
            <section key={s.category} className="mb-8">
              <h2 className="mb-3 text-lg font-semibold">{s.category}</h2>
              <ol className="space-y-3 pl-5 text-sm" style={{ listStyleType: "decimal" }}>
                {s.questions.map((q) => (
                  <li key={q.id}>
                    <p>
                      {q.mandatory && <span className="mr-1.5 rounded-full bg-red-50 px-1.5 py-0 text-[10px] font-medium uppercase tracking-wide text-red-700">Mandatory</span>}
                      {q.text}
                    </p>
                    {q.evidence_requested && <p className="mt-0.5 text-xs text-[var(--ink-600)]">Evidence required: {q.evidence_requested}</p>}
                    {q.rationale && <p className="mt-0.5 text-xs text-[var(--ink-500)]">Why this matters: {q.rationale}</p>}
                    <p className="mt-0.5 text-xs text-[var(--ink-400,#9ca3af)]">Weighting {q.weight}/5{q.priority === "required" ? " · required" : ""}</p>
                  </li>
                ))}
              </ol>
            </section>
          ))}

          {evidence.length > 0 && (
            <section className="mb-8">
              <h2 className="mb-2 text-lg font-semibold">Evidence checklist</h2>
              <p className="mb-2 text-sm text-[var(--ink-600)]">Vendors should return these artefacts with their response:</p>
              <ul className="list-disc space-y-1 pl-5 text-sm text-[var(--ink-800)]">
                {evidence.map((e) => (
                  <li key={e.item}>{e.item} <span className="text-xs text-[var(--ink-400,#9ca3af)]">({e.questionIds.length} {e.questionIds.length === 1 ? "question" : "questions"})</span></li>
                ))}
              </ul>
            </section>
          )}

          <section className="mb-8">
            <h2 className="mb-2 text-lg font-semibold">Scoring approach</h2>
            <p className="mb-3 text-sm text-[var(--ink-700)]">
              Responses are scored per question (1 to 5) multiplied by the question weighting. Mandatory questions are
              pass/fail gates: a failed mandatory excludes the response regardless of score.
            </p>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[var(--ink-200,#e5e5e5)] text-left text-xs uppercase tracking-wide text-[var(--ink-500)]">
                  <th className="py-1.5 pr-4">Section</th>
                  <th className="py-1.5 pr-4">Questions</th>
                  <th className="py-1.5 pr-4">Mandatory</th>
                  <th className="py-1.5">Weight share</th>
                </tr>
              </thead>
              <tbody>
                {stats.map((st) => (
                  <tr key={st.category} className="border-b border-[var(--ink-100,#f1f1f1)]">
                    <td className="py-1.5 pr-4">{st.category}</td>
                    <td className="py-1.5 pr-4">{st.questionCount}</td>
                    <td className="py-1.5 pr-4">{st.mandatoryCount}</td>
                    <td className="py-1.5">{(st.weightShare * 100).toFixed(0)}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          <section className="rounded-sm border border-[var(--ink-200,#e5e5e5)] p-4 text-xs text-[var(--ink-600)]">
            <p className="eyebrow mb-2">Provenance</p>
            <p className="mb-1">Generated by the Netify RFP Builder from methodology v{project.methodology_version}; question sources: Netify question bank v{BANK_VERSION} and the extended SASE canonical bank ({SASE_EXTENDED_BANK.question_bank_version}); see the <Link href="/rfp-builder/questions" className="underline">question bank</Link>.</p>
            <p>Suggested citation: <span className="font-medium">Netify Sample SASE / SD-WAN RFP {project.methodology_version}, Netify, available at {SITE_URL}/rfp-builder/sample-rfp/</span></p>
          </section>
        </article>

        <aside>
          <div className="sticky top-6 space-y-4">
            {/* The Continuation (DEF wave one): replaces the editorial
                Build-your-own buttons under One Door. Your position forms
                first; the Workspace recommends the formal Builder when the
                position warrants it. */}
            <Continuation
              c={deriveContinuationSampleRfp({ sampleTitle: `Netify Sample RFP ${project.methodology_version}` })}
              pageUrl={`${SITE_URL}/rfp-builder/sample-rfp`}
            />
            <div className="rounded-sm border border-[var(--ink-200,#e5e5e5)] p-5 text-sm">
              <p className="eyebrow mb-2">Related</p>
              <ul className="space-y-1.5">
                <li><Link href="/rfp-builder/questions" className="underline">The full question bank</Link></li>
                <li><a href="https://netify.co.uk/sd-wan/sample-rfp/" className="underline">SD-WAN sample RFP (routing, underlay, application performance, failover and managed operations)</a></li>
                <li><a href="https://netify.co.uk/sase-sd-wan-rfp-builder/" className="underline">Build an SD-WAN or SASE RFP</a></li>
                <li><Link href="/opportunities/sample-uk-retailer-sd-wan-managed-underlay" className="underline">The matching sample RFI</Link></li>
                <li><a href="https://netify.co.uk/methodology/" className="underline">Netify research methodology</a></li>
              </ul>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
