import type { Metadata } from "next";
import { FEATURES, FEATURE_NAMES, getShortlistDataset } from "@/lib/vendors";
import { buildShortlist, decodeScenario } from "@/lib/shortlist-core";
import PrintTrigger from "@/components/PrintTrigger";

export const metadata: Metadata = {
  title: "Your SASE shortlist (print version)",
  robots: { index: false, follow: false },
};

type Props = { searchParams: Promise<Record<string, string | string[] | undefined>> };

export default async function ShortlistPrintPage({ searchParams }: Props) {
  const params = await searchParams;
  const qs = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (typeof v === "string") qs.set(k, v);
  }
  const input = decodeScenario(qs.toString(), FEATURES.map((f) => f.id));
  const result = buildShortlist(getShortlistDataset(), input, FEATURE_NAMES);
  const today = new Date().toISOString().slice(0, 10);

  return (
    <div className="max-w-3xl mx-auto px-8 py-10 print:py-0 bg-white text-black">
      <PrintTrigger />
      <p className="eyebrow mb-2">Netify SASE and SD-WAN shortlist · {today}</p>
      <h1 className="mb-3">Your bespoke provider shortlist</h1>
      <p className="text-sm mb-1"><strong>Criteria.</strong> {result.criteria_summary}</p>
      <p className="text-sm mb-6">
        {result.shortlist.length} providers shortlisted from {result.considered} evaluated.
        Generated by the Netify shortlist builder.
      </p>

      <ol className="space-y-5 list-none p-0">
        {result.shortlist.map((v) => (
          <li key={v.slug} className="border-b border-gray-300 pb-4" style={{ breakInside: "avoid" }}>
            <p className="text-xs uppercase tracking-wide mb-1">
              No. {v.rank} · Score {v.score} · {v.category}
            </p>
            <h2 className="text-lg mb-1">{v.name}</h2>
            <p className="text-sm mb-2">{v.key_differentiators[0]}</p>
            {v.matched_requirements.length > 0 && (
              <p className="text-sm mb-1">
                <strong>Meets:</strong> {v.matched_requirements.join("; ")}
              </p>
            )}
            {v.gaps.length > 0 && (
              <p className="text-sm mb-1">
                <strong>Caveats:</strong> {v.gaps.join("; ")}
              </p>
            )}
            <p className="text-sm mb-1">
              <strong>Watch out:</strong> {v.watch_outs[0]}
            </p>
            <p className="text-sm">
              <strong>Commercials:</strong> {v.cost_model} · Typical deployment: {v.deployment_speed}
            </p>
          </li>
        ))}
      </ol>

      <p className="text-xs mt-8">{result.methodology_note}</p>
      <p className="text-xs mt-2">
        Published by Netify Group Limited, netify.co.uk. Extended dimension grades
        are indicative desk research; confirm capability via a structured RFP.
      </p>
    </div>
  );
}
