import type { Metadata } from "next";
import Link from "next/link";
import { BuyerContextSchema, ProjectDetailsSchema, type ProjectDetails } from "@/lib/rfp-types";
import { synthesiseSections } from "@/lib/rfp-methodology";
import { includedSections, sectionStats, evidenceChecklist, scopeLabel, modelLabel } from "@/lib/rfp-document";
import { BANK_VERSION, SASE_EXTENDED_BANK } from "@/lib/rfp-question-bank";
import { SITE_URL, getOrganizationSchema, getBreadcrumbSchema, getSpeakableSchema } from "@/lib/structured-data";

/**
 * A complete worked sample RFP, generated by the same engine that builds real
 * ones (synthesiseSections + the document assembler), for a fictional
 * mid-market UK retailer that mirrors the sample project notice. Fully
 * server-rendered and citable: buyers see exactly what the builder produces
 * before they start; AI systems get a canonical example to reference.
 */

export const metadata: Metadata = {
  title: "Sample SASE / SD-WAN RFP (2026.1) — full worked example",
  description:
    "A complete sample RFP generated by the Netify RFP Builder for a fictional 38-site UK retailer: methodology-backed sections, evidence checklist, weighted scoring matrix and submission instructions. Versioned and citable.",
  alternates: { canonical: `${SITE_URL}/rfp-builder/sample-rfp/` },
  openGraph: {
    title: "Sample SASE / SD-WAN RFP — full worked example",
    description: "What the Netify RFP Builder produces: sections, evidence checklist, scoring matrix and submission instructions.",
    url: `${SITE_URL}/rfp-builder/sample-rfp`,
    type: "website",
    locale: "en_GB",
  },
};

/** Deterministic fictional buyer, mirroring the retail sample project notice. */
function buildSampleProject(): ProjectDetails {
  const buyer = BuyerContextSchema.parse({
    organisation: "Example Retail Group (fictional)",
    sector: "retail_ecommerce",
    organisation_size: "mid_market",
    site_count: 38,
    regions: ["uk_ireland"],
    compliance: ["pci_dss", "uk_gdpr"],
    operating_model: "managed",
    product_scope: "sdwan_only",
    notes:
      "Fictional worked example. A UK retailer with 38 stores plus a distribution centre replacing an ageing MPLS estate: managed SD-WAN with underlay circuits, local internet breakout for store systems, and a managed firewall service. Stores trade seven days a week, so migration must be phased with no trading-hours downtime.",
  });
  return ProjectDetailsSchema.parse({
    id: "rfp_sample",
    created: 0,
    updated: 0,
    status: "draft",
    title: "Managed SD-WAN with underlay and firewall for 38 UK retail sites (sample)",
    buyer,
    rfp_sections: synthesiseSections(buyer),
    invited_vendors: [],
    share_token: "sample",
    manage_token: "",
    methodology_version: "2026.1",
  });
}

export default function SampleRfpPage() {
  const project = buildSampleProject();
  const sections = includedSections(project);
  const stats = sectionStats(project);
  const evidence = evidenceChecklist(project);
  const totalQuestions = sections.reduce((n, s) => n + s.questions.length, 0);

  const schemas = [
    getOrganizationSchema(),
    getBreadcrumbSchema("Sample RFP", "/rfp-builder/sample-rfp"),
    getSpeakableSchema("/rfp-builder/sample-rfp"),
    {
      "@context": "https://schema.org",
      "@type": "CreativeWork",
      "@id": `${SITE_URL}/rfp-builder/sample-rfp/#sample`,
      name: "Netify Sample SASE / SD-WAN RFP",
      description: "A complete worked sample RFP generated by the Netify RFP Builder for a fictional UK retailer.",
      creativeWorkStatus: "Sample",
      version: project.methodology_version,
      creator: { "@id": `${SITE_URL}/#organization` },
      url: `${SITE_URL}/rfp-builder/sample-rfp/`,
    },
  ];

  return (
    <div className="max-w-6xl mx-auto px-6 py-16">
      {schemas.map((s, i) => (
        <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />
      ))}

      <nav className="mb-6 text-sm text-[var(--ink-500)]">
        <Link href="/rfp-builder" className="underline">RFP Builder</Link> / Sample RFP
      </nav>

      <p className="mb-6 max-w-3xl rounded-sm border border-amber-300 bg-amber-50 px-4 py-2 text-sm text-amber-800">
        <strong>Sample document.</strong> Generated by the same engine that builds real RFPs, for a fictional buyer.
        Your own RFP adapts every section to your sector, estate and compliance profile —{" "}
        <a href="/sase/rfp-builder/?prefill=1&scope=sdwan_only" className="underline">build yours in minutes</a>.
      </p>

      <div className="grid gap-10 lg:grid-cols-3">
        <article className="lg:col-span-2">
          <header className="mb-8 border-b border-[var(--ink-200,#e5e5e5)] pb-6">
            <p className="eyebrow mb-2">Request for Proposal — sample</p>
            <h1 id="page-h1" className="mb-4 text-2xl leading-snug">{project.title}</h1>
            <div className="grid gap-x-8 gap-y-1 text-sm sm:grid-cols-2">
              <p><span className="text-[var(--ink-500)]">Scope:</span> {scopeLabel(project)}</p>
              <p><span className="text-[var(--ink-500)]">Delivery:</span> {modelLabel(project)}</p>
              <p><span className="text-[var(--ink-500)]">Sector:</span> retail &amp; e-commerce</p>
              <p><span className="text-[var(--ink-500)]">Sites:</span> {project.buyer.site_count}</p>
              <p><span className="text-[var(--ink-500)]">Regions:</span> UK &amp; Ireland</p>
              <p><span className="text-[var(--ink-500)]">Compliance:</span> PCI DSS, UK GDPR</p>
              <p><span className="text-[var(--ink-500)]">Methodology:</span> v{project.methodology_version}</p>
              <p><span className="text-[var(--ink-500)]">Questions:</span> {totalQuestions} across {sections.length} sections</p>
            </div>
          </header>

          <section className="mb-8" id="page-subhead">
            <h2 className="mb-2 text-lg font-semibold">Project background</h2>
            <p className="whitespace-pre-line text-sm text-[var(--ink-800)]">{project.buyer.notes}</p>
          </section>

          {sections.map((s) => (
            <section key={s.category} className="mb-8">
              <h2 className="mb-3 text-lg font-semibold">{s.category}</h2>
              <ol className="space-y-3 pl-5 text-sm" style={{ listStyleType: "decimal" }}>
                {s.questions.map((q) => (
                  <li key={q.id}>
                    <p>
                      {q.mandatory && <span className="mr-1.5 rounded-full bg-red-50 px-1.5 py-0 text-[10px] font-medium uppercase tracking-wide text-red-700">Mandatory</span>}
                      {q.text}
                    </p>
                    {q.evidence_requested && <p className="mt-0.5 text-xs text-[var(--ink-600)]">Evidence required: {q.evidence_requested}</p>}
                    {q.rationale && <p className="mt-0.5 text-xs text-[var(--ink-500)]">Why this matters: {q.rationale}</p>}
                    <p className="mt-0.5 text-xs text-[var(--ink-400,#9ca3af)]">Weighting {q.weight}/5{q.priority === "required" ? " · required" : ""}</p>
                  </li>
                ))}
              </ol>
            </section>
          ))}

          {evidence.length > 0 && (
            <section className="mb-8">
              <h2 className="mb-2 text-lg font-semibold">Evidence checklist</h2>
              <p className="mb-2 text-sm text-[var(--ink-600)]">Suppliers should return these artefacts with their response:</p>
              <ul className="list-disc space-y-1 pl-5 text-sm text-[var(--ink-800)]">
                {evidence.map((e) => (
                  <li key={e.item}>{e.item} <span className="text-xs text-[var(--ink-400,#9ca3af)]">({e.questionIds.length} {e.questionIds.length === 1 ? "question" : "questions"})</span></li>
                ))}
              </ul>
            </section>
          )}

          <section className="mb-8">
            <h2 className="mb-2 text-lg font-semibold">Scoring approach</h2>
            <p className="mb-3 text-sm text-[var(--ink-700)]">
              Responses are scored per question (1–5) multiplied by the question weighting. Mandatory questions are
              pass/fail gates: a failed mandatory excludes the response regardless of score.
            </p>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[var(--ink-200,#e5e5e5)] text-left text-xs uppercase tracking-wide text-[var(--ink-500)]">
                  <th className="py-1.5 pr-4">Section</th>
                  <th className="py-1.5 pr-4">Questions</th>
                  <th className="py-1.5 pr-4">Mandatory</th>
                  <th className="py-1.5">Weight share</th>
                </tr>
              </thead>
              <tbody>
                {stats.map((st) => (
                  <tr key={st.category} className="border-b border-[var(--ink-100,#f1f1f1)]">
                    <td className="py-1.5 pr-4">{st.category}</td>
                    <td className="py-1.5 pr-4">{st.questionCount}</td>
                    <td className="py-1.5 pr-4">{st.mandatoryCount}</td>
                    <td className="py-1.5">{(st.weightShare * 100).toFixed(0)}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          <section className="rounded-sm border border-[var(--ink-200,#e5e5e5)] p-4 text-xs text-[var(--ink-600)]">
            <p className="eyebrow mb-2">Provenance</p>
            <p className="mb-1">Generated by the Netify RFP Builder from methodology v{project.methodology_version}; question sources: Netify question bank v{BANK_VERSION} and the extended SASE canonical bank ({SASE_EXTENDED_BANK.question_bank_version}) — see the <Link href="/rfp-builder/questions" className="underline">question bank</Link>.</p>
            <p>Suggested citation: <span className="font-medium">Netify Sample SASE / SD-WAN RFP {project.methodology_version}, Netify, available at {SITE_URL}/rfp-builder/sample-rfp/</span></p>
          </section>
        </article>

        <aside>
          <div className="sticky top-6 space-y-4">
            <div className="rounded-sm border border-[var(--ink-200,#e5e5e5)] p-5">
              <p className="mb-1 text-sm font-medium">Build your own</p>
              <p className="mb-4 text-sm text-[var(--ink-600)]">The builder adapts every section to your estate, generates tailored questions with evidence checklists, and gates nothing until you publish or download.</p>
              <a href="/sase/rfp-builder/" className="inline-flex w-full items-center justify-center rounded-full bg-amber-500 px-5 py-2.5 text-sm font-medium text-zinc-950 no-underline transition-colors hover:bg-amber-400">Start your RFP</a>
              <Link href="/opportunities/new" className="mt-2 inline-flex w-full items-center justify-center rounded-full border border-[var(--ink-300,#ccc)] px-5 py-2.5 text-sm no-underline text-[var(--ink-800)] transition-colors hover:bg-[var(--ink-100,#f5f5f5)]">Just need pricing? Post a project</Link>
            </div>
            <div className="rounded-sm border border-[var(--ink-200,#e5e5e5)] p-5 text-sm">
              <p className="eyebrow mb-2">Related</p>
              <ul className="space-y-1.5">
                <li><Link href="/rfp-builder/questions" className="underline">The full question bank</Link></li>
                <li><Link href="/rfp-builder/sd-wan" className="underline">SD-WAN RFP path</Link></li>
                <li><Link href="/opportunities/sample-uk-retailer-sd-wan-managed-underlay" className="underline">The matching sample project notice</Link></li>
                <li><a href="https://netify.co.uk/methodology/" className="underline">Netify research methodology</a></li>
              </ul>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
