import { ProjectDetailsSchema } from '../src/lib/rfp-types';
import { compileProcurementDocument } from '../src/lib/workspace/procurement-document';
import { factId, requirementFrom, type WorkspaceFact } from '../src/lib/workspace/draft';
export function fact(path:WorkspaceFact['path'],value:unknown,extra:Partial<WorkspaceFact>={}):WorkspaceFact {return {id:factId(path,value),path,value,provenance:'stated',struck:false,source:'answer',cycle:1,...extra};}
export function documentFor(facts:WorkspaceFact[]) {return compileProcurementDocument({facts,requirement:requirementFrom(facts),verdict:null,noted:[],rfiSet:null,instrument:'sor',receipts:[],previousDocument:null});}
export function canonicalFixture(mode:'quick_list'|'find_providers'='find_providers') {
 const facts=[fact('estate.users',2),fact('estate.sites',2),fact('constraints.timeline','Within two months'),fact('organisation.sector','manufacturing'),fact('organisation.regions','uk'),fact('procurement.buying','sdwan'),fact('procurement.operatingModel','managed'),fact('estate.existingNetwork','broadband'),fact('drivers','Reduce outages affecting customer orders'),fact('requirements.bespoke','Maintain customer-order connectivity during migration')];
 return ProjectDetailsSchema.parse({id:`rfp_canonical_${mode}`,title:'Private Buyer Ltd: resilient connectivity for customer orders',owner_email:'owner@buyer.example',created:1,updated:1,share_token:`share_${mode}`,manage_token:`manage_${mode}`,facts,procurement_document:documentFor(facts),buyer:{organisation:'Private Buyer Ltd',sector:'retail_ecommerce',site_count:99,regions:['asia_pacific'],operating_model:'diy',product_scope:'full_sase',notes:'No supplier requirements have been created yet. PRIVATE-DOCUMENT-CANARY.'},journey:{contract_version:'project-journey/1.0.0',source:'shortlist',source_url:'https://netify.co.uk/sase/shortlist/',mode,started_at:1},entrance_context:{version:'project-entrance/1.0.0',source:'shortlist',captured_at:1,raw_input:{timescale:'Next year'}}});
}
