import assert from 'node:assert/strict';
import definitions from '../data/feature-definitions.json';
import { researchMetrics } from '../src/lib/research-metrics';
import { buyerDecisionGuide } from '../src/lib/buyer-decision-guide';
import type { ShortlistVendor } from '../src/lib/shortlist-core';
const ids=definitions.features.map(f=>f.id);
const capabilities:ShortlistVendor['capabilities']={};
let metrics=researchMetrics({capabilities});
assert.equal(metrics.total,40); assert.equal(metrics.unconfirmed,40); assert.equal(metrics.completeness,0);
['yes','partial','partner_integrated','managed_service_dependent','not_primary','not_confirmed','unknown'].forEach((grade,i)=>capabilities[ids[i]]=grade as never);
capabilities.non_framework_field='yes';
metrics=researchMetrics({capabilities});
assert.equal(metrics.reviewed,5); assert.equal(metrics.supported,1); assert.equal(metrics.unconfirmed,35); assert.equal(metrics.completeness,5/40);
const base={slug:'test',name:'Test',last_verified:'2026-10-01',capabilities} as ShortlistVendor;
const groups=buyerDecisionGuide([base]);
assert.equal(groups[0].providers[0].grade,'yes');
assert.equal(groups[1].providers[0].grade,'partial');
assert.equal(groups[2].providers.length,0);
assert.equal(groups[0].providers[0].source_url,null);
console.log('PASS metric reconciliation, unsupported extra fields, missing evidence and conditional option grades');
import { parseResearchHandoff } from '../src/lib/research-handoff';
const handoff=(value:unknown)=>'#sourcing-context='+encodeURIComponent(JSON.stringify(value));
const context={version:1,requirement:'10 sites, including a factory & remote users',source:'https://netify.co.uk/insights/top-best-mpls-network-providers/'};
assert.deepEqual(parseResearchHandoff(handoff(context)),{requirement:context.requirement,source:context.source,provider_context:[]});
for(const patch of [{source:'https://evil.test/insights/test/'},{source:context.source+'?email=private'},{version:2},{requirement:'x'.repeat(12001)}]) assert.equal(parseResearchHandoff(handoff({...context,...patch})),null);
assert.equal(parseResearchHandoff('#sourcing-context=%invalid'),null);
console.log('PASS private article handoff validation and no recipient authority');
import {approvedEditorialReview,providerEvidenceFingerprint} from '../src/lib/provider-editorial-review';
const evidence={...base,sectors:{},regions:{},uk_delivery:'not_confirmed'} as ShortlistVendor;
const review={buyer_fit:'Specific buyer context',strengths:['Sourced strength'],trade_offs:['Scope to confirm'],source_urls:['https://example.com/evidence'],reviewer:'Test reviewer',role:'Test role',approved_at:'2026-10-01',review_due:'2026-10-15',evidence_fingerprint:providerEvidenceFingerprint(evidence)};
const now=Date.parse('2026-10-02');
assert.deepEqual(approvedEditorialReview(evidence,review,now),review);
assert.equal(approvedEditorialReview({...evidence,last_verified:'2026-10-02'},review,now),null);
assert.equal(approvedEditorialReview(evidence,{...review,reviewer:''},now),null);
assert.equal(approvedEditorialReview(evidence,review,Date.parse('2026-10-16')),null);
assert.equal(approvedEditorialReview(evidence,review,Date.parse('2026-09-30')),null);
console.log('PASS editorial approval scope, changed evidence, empty reviewer and expiry guards');
