import assert from 'node:assert/strict';
import { ProjectDetailsSchema } from '../src/lib/rfp-types';
import { buildMarketReport } from '../src/lib/market-report';
import { shortProjectNotice } from '../src/lib/short-project';
import { aggregateFunnel } from '../src/lib/marketplace-funnel-report';
import { activityClassification } from '../src/lib/activity-provenance';
const fact = (path: string, value: unknown, struck = false) => ({id:path,path,value,struck,provenance:'stated',source:'answer',cycle:1});
const p = ProjectDetailsSchema.parse({id:'rfp_regression',title:'Synthetic regression',created:1,updated:1,share_token:'share',manage_token:'manage',buyer:{organisation:'Private buyer',notes:'No supplier requirements have been created yet. Describe what you need above to start building this document.'},facts:[fact('estate.users',2),fact('constraints.timeline','Within two months')]});
const report = buildMarketReport(p, []);
assert.equal(report.estimate,null);
assert(report.assumptions.some(a=>a.includes('2 users')));
assert(!report.assumptions.some(a=>a.includes('250 users')));
assert(!report.gaps.some(g=>g.includes('No timeline')));
const notice = shortProjectNotice(p);
assert(notice.summary.includes('2 users'));
assert.equal(notice.timeline_note,'Within two months');
assert(!notice.summary.includes('No supplier requirements'));
const removed = {...p, facts:p.facts.map(f=>({...f,struck:true}))};
assert.equal(buildMarketReport(removed,[]).estimate,null);
assert.equal(shortProjectNotice(removed).timeline_note,'');
const inferred = {...p, facts:[...p.facts,{...p.facts[0], id:'later',value:2000,provenance:'inferred' as const}]};
assert.equal(buildMarketReport(inferred,[]).estimate,null, 'an unconfirmed replacement must not resurrect an older stated number');
const now=Date.now();
const e={at:now,event:'project_started',project_id:'same',source:'shortlist',mode:'quick_list',channel:'web'};
const funnel=aggregateFunnel([{...e,environment:'production'},{...e,environment:'preview'},{...e,project_id:'legacy'},{...e,project_id:'qa',environment:'production',classification:'test'}],now);
assert.equal(funnel.counts.project_started,1);
assert.equal(funnel.environment_counts.preview.project_started,1);
assert.equal(funnel.environment_counts.unknown.project_started,1);
assert.equal(funnel.excluded_test_events,1);
assert.equal(activityClassification({buyer:{organisation:'Netify QA DO NOT PUBLISH'}}),'test');
assert.equal(activityClassification({buyer:{organisation:'ACME Ltd'}}),'unverified');
assert.equal(activityClassification({buyer:{organisation:'Test'},owner_email:'hyelland@netify.com'}),'test');
console.log('PASS current buyer facts, small-estate pricing, removed facts, test exclusions and environment separation');
