import assert from "node:assert/strict";
import { attentionItem, latestPublicationOutcomes, publicationBlocker, recoveryReminder } from "../src/lib/buyer-recovery";
const failed = {rfp_id:"one",at:1,state:"saved_unpublished",verification:{failed_check:"website"}};
assert.match(publicationBlocker(failed)!, /website check/);
const sent = recoveryReminder('<script>bad</script>', 'https://netify.co.uk/sase/account/?a=1&b=2', 'https://netify.co.uk/unsubscribe/', failed);
assert.match(sent.subject, /publication check/);
assert.match(sent.text, /does not bypass verification/);
assert.ok(!sent.html.includes('<script>'));
assert.ok(sent.html.includes('&amp;b=2'));
assert.ok(!sent.text.includes('vendors match'));
assert.equal(publicationBlocker(latestPublicationOutcomes([failed,{...failed,at:2,state:'published'}]).get('one')),null);
assert.equal(latestPublicationOutcomes([{...failed,at:2},failed]).get('one')?.at,2);
assert.match(recoveryReminder('draft','https://netify.co.uk','https://netify.co.uk').text,/does not guarantee/);
for(const check of ['mx','academic','free_or_disposable','other']) assert.ok(publicationBlocker({...failed,verification:{failed_check:check}}));
console.log('PASS buyer recovery: latest state, scoped failures, safe copy, HTML escaping, no supplier promises');
const project = {id:'one',title:'Project',owner_email:'buyer@example.org',status:'draft',updated:2};
assert.match(attentionItem(project,failed,0)!.status,/blocked/);
assert.equal(attentionItem(project,undefined,0),null);
assert.match(attentionItem({...project,status:'published'},failed,0)!.status,/handoff/);
assert.equal(attentionItem({...project,status:'published'},failed,1),null);
console.log('PASS attention queue: blocked, ordinary draft, zero connections, resolved handoff');
