import assert from 'node:assert/strict';
import fs from 'node:fs';
import { buildShortlist, ShortlistInputSchema } from '../src/lib/shortlist-core';
import { getShortlistDataset } from '../src/lib/vendors';
import { sectorUnconfirmedCoverage, coverageExplanation } from '../src/lib/coverage-preview';
import { privateDraftMarkdown, printableDraftHtml, briefDraftMarkdown } from '../src/lib/private-draft';
import { renderRfpDocxBlob } from '../src/lib/rfp-export-docx';
import { quickListingReadiness } from '../src/lib/publication-policy';
import type { LivingProcurementDocument } from '../src/lib/workspace/procurement-document';

const vendors = getShortlistDataset().slice(0,8).map(v => ({...v, regions:{...v.regions,uk_ireland:'yes' as const}, sectors:{...v.sectors,professional_services:'unknown' as const}}));
const input=ShortlistInputSchema.parse({sector:'professional_services',required_regions:['uk_ireland'],shortlist_size:3});
assert.equal(buildShortlist(vendors,input).shortlist.length,0);
assert.equal(sectorUnconfirmedCoverage(vendors,input),8,'coverage is not truncated to shortlist length');
assert.equal(sectorUnconfirmedCoverage(vendors.map(v=>({...v,sectors:{...v.sectors,professional_services:'not_primary'}})),input),0,'negative sector evidence must not become pending matches');
assert.equal(sectorUnconfirmedCoverage(vendors.map(v=>({...v,regions:{...v.regions,uk_ireland:'unknown'}})),input),0,'must retain region gate');
assert.match(coverageExplanation({meets_all_mandatory_count:0,sector_unconfirmed_count:8,considered_count:8}),/no fully verified matches/i);
assert.match(coverageExplanation({meets_all_mandatory_count:0,considered_count:8}),/does not prove/);
const brief={scope:'sase',sector:'professional_services',sites:'5',regions:['uk_ireland'],operatingModel:'any',outcome:'Replace VPN with managed SD-WAN and SASE for five offices.',timescale:'Within three months',company:'Private Test Ltd',requiredFeatures:[]};
assert.equal(quickListingReadiness({solutionScope:brief.scope,sector:brief.sector,siteCount:5,regions:brief.regions,operatingModel:brief.operatingModel,outcome:brief.outcome,timescale:brief.timescale}).allowed,true);
assert.match(briefDraftMarkdown(brief),/PRIVATE WORKING DRAFT/);
assert.ok(!briefDraftMarkdown(brief).includes(brief.company),'brief download omits private company field');
const doc={title:'Draft <script>alert(1)</script>',summary:'Original requirement',clauses:[{id:'R1',statement:'Keep buyer requirement verbatim',evidence:['Proof required'],reason:'Buyer stated'}],responseGroups:[{title:'Supplier questions',questions:[{text:'Custom question retained?',evidenceRequested:['Custom evidence']}]}],openDecisions:[{question:'Which identity provider?',conflictReason:null}]} as LivingProcurementDocument;
const md=privateDraftMarkdown(doc);
for(const text of ['Original requirement','Keep buyer requirement verbatim','Custom question retained?','Custom evidence','Which identity provider?','not published'])assert.ok(md.includes(text));
const html=printableDraftHtml(doc.title,md);
assert.ok(!html.includes('<script>'),'user text cannot become script');assert.ok(html.includes('&lt;script&gt;'));
const bytes=Buffer.from(await (await renderRfpDocxBlob(md,doc.title)).arrayBuffer());
assert.equal(bytes.subarray(0,2).toString(),'PK');assert.ok(bytes.length>3000);
fs.writeFileSync('/tmp/netify-private-draft-test.docx',bytes);
console.log('PASS: unknown vs negative evidence, all eligible counts, short-brief readiness, content preservation, escaped printable draft and native Word export');
