import assert from 'node:assert/strict';
import { deterministicExtract } from '../src/lib/workspace/extract';
import { mergeUpdates, requirementFrom, buyingOf } from '../src/lib/workspace/draft';
import { assessSecurityRequirement } from '../src/lib/security/rulebook';
import { deriveRfiQuestionSet } from '../src/lib/workspace/instrument';
import { compileProcurementDocument } from '../src/lib/workspace/procurement-document';
import { buildEnvelopeUpdate } from '../src/lib/workspace/envelope';
const text='We are a retail business with 15 sites in the UK and 30 remote users. We need managed SASE within six months.';
const facts=mergeUpdates([],deterministicExtract(text),1).facts;
const requirement=requirementFrom(facts); const buying=buyingOf(facts);
const verdict=buying==='managed_security'||buying===null?await assessSecurityRequirement(requirement):null;
const input={facts,requirement,verdict,noted:[],rfiSet:deriveRfiQuestionSet({coveredSections:[],sector:requirement.organisation?.sector??null}),instrument:'sor' as const,receipts:[],sourceTurns:[]};
let client=compileProcurementDocument({...input,previousDocument:null,revision:{cycle:1,changedFactIds:[]}});
for(let cycle=2;cycle<=4;cycle++)client=compileProcurementDocument({...input,previousDocument:client,revision:{cycle,changedFactIds:[]}});
const body={facts,receipts:[],instrument:'sor',compiled_document:client,base_revision:0};
const params={body,mergedSourceLedger:[],mergedDecisionLedger:[],coveredSections:[],savedBy:'test'};
const first=await buildEnvelopeUpdate({...params,existing:null});assert(first.participates&&first.ok,'Multiple local revisions must save');if(!first.participates||!first.ok)throw Error('save failed');assert.equal(first.procurement_document.version,1);
const second=await buildEnvelopeUpdate({...params,body:{...body,base_revision:1},existing:{procurement_document:first.procurement_document,envelope_revision:1}});assert(second.participates&&second.ok,'Repeat save must work against durable history');
const stale=await buildEnvelopeUpdate({...params,existing:{procurement_document:first.procurement_document,envelope_revision:1}});assert(stale.participates&&!stale.ok&&stale.status===409);
const tampered=structuredClone(client);tampered.clauses[0].statement='Unapproved invented requirement';
const bad=await buildEnvelopeUpdate({...params,body:{...body,compiled_document:tampered},existing:null});assert(bad.participates&&!bad.ok,'Content tampering must still be rejected');
console.log('PASS first save after four local revisions; repeat save; stale revision rejection; content tampering rejection');
const {preserveMarketplaceWorkspace} = await import('../src/lib/marketplace-workspace-envelope');
const persisted = await preserveMarketplaceWorkspace(null,{workspace_payload:body,document_purpose:'brief'});
const sections = ('rfp_sections' in persisted ? persisted.rfp_sections : []) as import('../src/lib/rfp-types').RfpSection[];
assert(sections.length>0,'Supplier question projection must accompany a workspace save');
assert.equal(sections.reduce((n,s)=>n+s.questions.length,0),first.procurement_document.clauses.length);
console.log('PASS saved workspace includes every canonical supplier clause');
