// @ts-expect-error Node 24 test runtime exposes registerHooks; project types target Node 20.
import { registerHooks } from 'node:module';
registerHooks({resolve(specifier: string, context: object, next: (s: string, c: object) => {url: string}) { return specifier === 'server-only' ? {url:'data:text/javascript,export {};',shortCircuit:true} : next(specifier,context); }});
import assert from 'node:assert/strict';
import { withFakeKv } from './fake-kv-harness';
import { compileProcurementDocument } from '../src/lib/workspace/procurement-document';
import { mergeUpdates, requirementFrom } from '../src/lib/workspace/draft';
import { deterministicExtract } from '../src/lib/workspace/extract';
import { deriveRfiQuestionSet } from '../src/lib/workspace/instrument';
import { replayDecisionLedger, type DecisionLedgerEntry } from '../src/lib/workspace/decision-ledger';
import type { SourceLedgerEntry } from '../src/lib/workspace/source-ledger';

await withFakeKv(async () => {
 const {startMarketplaceProject,updateMarketplaceProject,readMarketplaceProject,prepareMarketplacePublication}=await import('../src/lib/marketplace-project-session');
 const {getProject}=await import('../src/lib/rfp-store');
 const {rfpBuilderEntrance}=await import('../src/lib/project-entrance');
 const {shortProjectReadiness}=await import('../src/lib/short-project');
 const {MARKETPLACE_PUBLICATION_CONSENT_TEXT,MARKETPLACE_PUBLICATION_CONSENT_VERSION}=await import('../src/lib/publication-policy');
 const text='We are a manufacturing business with 15 sites in the UK. We need SASE for 30 remote users.';
 const facts=mergeUpdates([],deterministicExtract(text),1).facts;
 const source:SourceLedgerEntry[]=[{id:'source-one',text:'  Original RFI\r\n'+text+'\r\nDo not remove the appendix.  ',at:1,via:'file'}];
 const question='Demonstrate OT failover without interrupting production.';
 const decisions:DecisionLedgerEntry[]=[{id:'decision-one',at:2,questionId:'custom-supplier-question:resilience_availability:demo',optionId:'custom_supplier_question',optionLabel:question,action:'note',resultingFactPaths:[],resultingNoted:[{id:'custom-supplier-question:resilience_availability:demo',label:question,section:'resilience_availability',own:true}]}];
 const requirement=requirementFrom(facts);
 const doc=compileProcurementDocument({facts,requirement,verdict:null,noted:replayDecisionLedger(decisions).noted,rfiSet:deriveRfiQuestionSet({coveredSections:[],sector:requirement.organisation?.sector??null}),instrument:'rfi',receipts:[],sourceTurns:source,previousDocument:null,revision:null});
 const workspace={facts,receipts:[],instrument:'rfi',source_turns:source,decision_turns:decisions,compiled_document:doc,base_revision:0,position:{covered_sections:[]}};
 const buyer={organisation:'Manufacturing Test Company',sector:'manufacturing',site_count:15,regions:['uk_ireland'],operating_model:'managed',product_scope:'full_sase',notes:'Connect fifteen manufacturing sites with resilient managed SASE and SD-WAN.'};
 const entrance=rfpBuilderEntrance({rawInput:{buyer,requirement_text:buyer.notes,solution_scope:'sase',timescale:'Within six months',workspace_payload:workspace,document_purpose:'rfi'}});
 const started=await startMarketplaceProject({mode:'quick_list',entrance_context:entrance});
 assert.equal(started.envelope_revision,1);
 let read=await readMarketplaceProject(started.project_reference,started.project_session_token);
 assert.equal(read.envelope_revision,1); assert.equal(read.workspace_payload?.base_revision,1);
 assert.equal(read.workspace_payload?.source_turns[0].text,source[0].text);
 assert.equal(read.entrance_context?.raw_input.document_purpose,'rfi');
 assert(JSON.stringify(read.workspace_payload?.compiled_document).includes(question));
 let stored=(await getProject(started.project_reference))!;
 assert(shortProjectReadiness(stored).allowed, 'optional full-RFP gaps must not block brief eligibility');
 assert.equal(stored.decision_ledger.length,1);
 read.workspace_payload!.compiled_document=compileProcurementDocument({facts,requirement,verdict:null,noted:replayDecisionLedger(decisions).noted,rfiSet:deriveRfiQuestionSet({coveredSections:[],sector:requirement.organisation?.sector??null}),instrument:'rfi',receipts:[],sourceTurns:source,previousDocument:stored.procurement_document ?? null,revision:null});
 const patch={base_revision:0,idempotency_key:'workspace-save-001',buyer_patch:{},raw_input:{workspace_payload:read.workspace_payload,document_purpose:'rfi'}};
 const updated=await updateMarketplaceProject(started.project_reference,started.project_session_token,patch);
 assert.equal(updated.revision,1); assert.equal(updated.envelope_revision,2);
 assert.deepEqual(await updateMarketplaceProject(started.project_reference,started.project_session_token,patch),updated);
 await assert.rejects(()=>updateMarketplaceProject(started.project_reference,started.project_session_token,{...patch,base_revision:1,idempotency_key:'workspace-stale-envelope'}),/saved since|base revision/);
 await assert.rejects(()=>updateMarketplaceProject(started.project_reference,started.project_session_token,{...patch,idempotency_key:'workspace-stale-session'}),/Revision conflict/);
 read=await readMarketplaceProject(started.project_reference,started.project_session_token);
 const tampered=structuredClone(read.workspace_payload!); tampered.compiled_document.title='Forged server document';
 await assert.rejects(()=>updateMarketplaceProject(started.project_reference,started.project_session_token,{base_revision:1,idempotency_key:'workspace-forged-document',raw_input:{workspace_payload:tampered}}),/does not correspond/);
 const simple=await updateMarketplaceProject(started.project_reference,started.project_session_token,{base_revision:1,idempotency_key:'workspace-brief-only',buyer_patch:{notes:buyer.notes+' Protect OT.'},raw_input:{timescale:'Within six months'}});
 assert.equal(simple.envelope_revision,2);
 stored=(await getProject(started.project_reference))!;
 assert.equal(stored.source_ledger[0].text,source[0].text); assert.equal(stored.decision_ledger.length,1);
 assert(JSON.stringify(stored.procurement_document).includes(question));
 assert.equal(stored.entrance_context?.raw_input.document_purpose,'rfi');
 const prepared=await prepareMarketplacePublication(started.project_reference,started.project_session_token,{base_revision:simple.revision,consent_version:MARKETPLACE_PUBLICATION_CONSENT_VERSION,consent_text:MARKETPLACE_PUBLICATION_CONSENT_TEXT});
 assert.equal(prepared.revision,simple.revision+1);
 console.log('PASS canonical marketplace workspace: bespoke/source retention, recomputation, independent revision conflicts, idempotency and brief readiness');
});
