import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {deterministicExtract} from '../src/lib/workspace/extract';
import {mergeUpdates} from '../src/lib/workspace/draft';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
const source='We are a manufacturing business with 15 sites, 10 in the UK and five global sites, and 30 remote users. We need managed SASE within six months. Preserve production availability and protect OT.';
const fixture={schema:1,id:'rollout-test',updatedAt:Date.now(),facts:mergeUpdates([],deterministicExtract(source),1).facts,noted:[],receipts:[],sourceTurns:[{id:'source-test',text:source,at:1,via:'typed'}],decisionTurns:[],dismissedQuestionIds:[],declinedSuggestionIds:[],resumeRemovals:[],messages:[],rfpDepth:'detailed',rfpEntryMode:'build',rfpValidationCorpus:'',documentPurpose:'rfi',pinnedVendorSlugs:['cato-networks']};
try {
 await page.goto(process.env.TEST_URL||'http://localhost:3107/sase/home/');
 await page.evaluate(f=>{localStorage.clear();localStorage.setItem('netify_living_rfp_active_draft_v1',f.id);localStorage.setItem('netify_living_rfp_draft_v1_'+f.id,JSON.stringify(f));},fixture);
 await page.reload();await page.getByRole('button',{name:'Resume saved project',exact:true}).click();
 await page.getByRole('button',{name:'Requirements & RFP',exact:true}).click();
 await page.locator('.nf-guided-register > summary').click();
 await page.getByRole('button',{name:'＋ Add bespoke question',exact:true}).click();
 const bespoke='Demonstrate failover without interrupting our production lines?';
 await page.getByLabel('Question for suppliers',{exact:true}).fill(bespoke);
 await page.locator('.nf-guided-add-question').getByRole('button',{name:'Add',exact:true}).click();
 await page.getByRole('button',{name:'Review & publish →',exact:true}).first().click();
 await page.getByLabel('Number of sites',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('Number of sites',{exact:true}).inputValue(),'15');
 assert.equal(await page.getByLabel('Sector',{exact:true}).inputValue(),'manufacturing');
 await page.getByLabel('Company name (private)',{exact:true}).fill('Manufacturing Test Company');
 await page.getByLabel('Buying timescale',{exact:true}).fill('Within six months');
 let captured:any;
 await page.route('**/api/marketplace/projects',async route=>{captured=route.request().postDataJSON();await route.fulfill({status:201,json:{project_reference:'test-project',project_session_token:'test-only',revision:0,envelope_revision:1}})});
 await page.getByRole('button',{name:'Review my project',exact:true}).click();
 await page.getByRole('heading',{name:'Review your anonymous project notice',exact:true}).waitFor();
 writeFileSync('/tmp/netify-shared-workspace-fixture.json',JSON.stringify(captured));
 const payload=captured.entrance_context.raw_input.workspace_payload;
 assert(payload.source_turns.some((s:any)=>s.text===source));assert(JSON.stringify(payload.decision_turns).includes(bespoke));assert(JSON.stringify(payload.compiled_document).includes(bespoke));
 assert.equal(captured.entrance_context.raw_input.document_purpose,'rfi');
 assert.deepEqual(captured.entrance_context.buyer_input.pinned_vendors,['cato-networks']);
 assert(payload.facts.some((f:any)=>f.path==='estate.sites'&&f.value===15));
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS browser: explicit resume, sector/sites prefill, exact source and bespoke question preserved through short brief review; RFI purpose retained; no runtime errors. No server writes.');
} finally {await browser.close();}
