import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const input=JSON.parse(readFileSync('/tmp/netify-shared-workspace-fixture.json','utf8'));
const payload=input.entrance_context.raw_input.workspace_payload;
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
let revision=1,published=false;
const key='netify_project_checkpoint_v1_checkpoint-test';
const data=()=>({project_reference:'checkpoint-test',revision:0,envelope_revision:revision,buyer:input.entrance_context.buyer_input,entrance_context:input.entrance_context,workspace_payload:{...payload,base_revision:revision},marketplace_state:{publication_status:published?'published':'draft'}});
try{
 await page.route('**/api/marketplace/projects/checkpoint-test*',route=>route.fulfill({json:data()}));
 await page.goto('http://localhost:3107/sase/home/?project=checkpoint-test#project_session=test-only');
 await page.getByRole('button',{name:'Close project brief',exact:true}).click({timeout:1000}).catch(()=>{});
 await page.locator('textarea').first().waitFor();
 await page.waitForFunction(()=>{const detail:{value?:{id?:string;busy?:boolean}}={};window.dispatchEvent(new CustomEvent('netify:project-read',{detail}));return detail.value?.id==='checkpoint-test'&&!detail.value.busy;});
 await page.evaluate(()=>localStorage.setItem('netify_living_rfp_active_draft_v1','unrelated'));
 const prompt=page.locator('textarea').first();
 await prompt.fill('Correct remote users to 40');await page.getByRole('button',{name:'Send',exact:true}).click();
 await page.waitForFunction(k=>{const p=JSON.parse(localStorage.getItem(k)||'null');return p?.snapshot.facts.some((f:{path:string;value:number;struck:boolean})=>f.path==='estate.users'&&f.value===40&&!f.struck)},key);
 await prompt.pressSequentially('Do not lose this unsent manufacturing requirement.',{delay:20});
 await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)||'null')?.snapshot.draftInput?.includes('unsent manufacturing'),key);
 const checkpoint=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!),key);
 assert.equal(checkpoint.baseRevision,1);assert.equal(checkpoint.projectId,'checkpoint-test');
 assert.equal(await page.evaluate(()=>localStorage.getItem('netify_living_rfp_active_draft_v1')),'unrelated');
 await page.reload();await page.getByRole('button',{name:'Close project brief',exact:true}).click({timeout:1000}).catch(()=>{});await page.getByRole('button',{name:'Resume device changes',exact:true}).click();
 assert.equal(await page.locator('textarea').first().inputValue(),'Do not lose this unsent manufacturing requirement.');
 const restored=await page.evaluate(()=>{const detail:{value?:unknown}={};window.dispatchEvent(new CustomEvent('netify:project-read',{detail}));return detail.value}) as {payload:{facts:unknown[];source_turns:unknown[];decision_turns:unknown[];position:{rfp_depth:string}}};
 assert.deepEqual(restored.payload.facts,checkpoint.snapshot.facts);assert.deepEqual(restored.payload.source_turns,checkpoint.snapshot.sourceTurns);assert.deepEqual(restored.payload.decision_turns,checkpoint.snapshot.decisionTurns);assert.equal(restored.payload.position.rfp_depth,checkpoint.snapshot.rfpDepth);
 revision=2;await page.reload();await page.getByRole('button',{name:'Close project brief',exact:true}).click({timeout:1000}).catch(()=>{});await page.getByRole('heading',{name:'Your project has changed since this recovery copy',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Resume device changes',exact:true}).count(),0);
 assert.equal((await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!),key)).baseRevision,1);
 await page.getByRole('button',{name:'Use saved server version',exact:true}).click();await page.locator('textarea').first().waitFor();
 assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),null);
 await page.evaluate(({k,c})=>localStorage.setItem(k,JSON.stringify(c)),{k:key,c:{...checkpoint,baseRevision:2}});
 published=true;await page.reload();await page.getByRole('button',{name:'Close project brief',exact:true}).click({timeout:1000}).catch(()=>{});await page.getByRole('heading',{name:'Your project has changed since this recovery copy',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Resume device changes',exact:true}).count(),0);
 assert.deepEqual(errors,[]);
 console.log('PASS private per-project checkpoint: facts, exact source, bespoke decisions, depth and unsent text survive explicit reload recovery; unrelated pointer untouched; changed revision and published project cannot restore. GET mocked; no real writes.');
}finally{await browser.close();}
