import {z} from 'zod';
import {sessionFromRequest} from '@/lib/auth';import {isAdminEmail} from '@/lib/access-control';
import {readActivityReportingRecords} from '@/lib/activity-report-reader';import {weeklyActivityReport,normaliseEnvironment} from '@/lib/activity-weekly-report';
import {readActivityAudit,correctActivity} from '@/lib/activity-audit';import {kvGetJson} from '@/lib/rfp-store';import {createActivity,type ActivityMetadata} from '@/lib/activity-provenance';
export const dynamic='force-dynamic';const headers={'Cache-Control':'private, no-store','X-Robots-Tag':'noindex'};
async function admin(req:Request){const s=await sessionFromRequest(req);return s&&isAdminEmail(s.email)?s:null;}
export async function GET(req:Request){if(!await admin(req))return Response.json({error:'Admin access required'},{status:403,headers});
 try{const q=new URL(req.url).searchParams;const start=Date.parse(q.get('start')??'2026-09-05T23:00:00Z'),end=Date.parse(q.get('end')??'2026-09-12T23:00:00Z'),asOf=Date.parse(q.get('as_of')??new Date().toISOString());const data=await readActivityReportingRecords();return Response.json({...weeklyActivityReport(data.records,data.events,start,end,asOf),limitations:data.limitations,unresolved_joins:data.unresolved_joins},{headers});}catch{return Response.json({error:'Report unavailable; no zero counts substituted'},{status:503,headers});}}
const Correction=z.object({project_id:z.string().regex(/^[a-zA-Z0-9_-]{1,100}$/),expected_version:z.number().int().min(0),classification:z.enum(['test','non_test','unknown']).optional(),buyer_intent:z.boolean().optional(),evidence_ref:z.string().max(200).optional(),reason:z.string().trim().min(3).max(500)}).strict();
export async function PATCH(req:Request){const actor=await admin(req);if(!actor)return Response.json({error:'Admin access required'},{status:403,headers});
 try{const body=Correction.parse(await req.json());const p=await kvGetJson<{activity?:ActivityMetadata;activity_environment?:string}>(`rfp:${body.project_id}`);if(!p)return Response.json({error:'Record not found'},{status:404,headers});const env=normaliseEnvironment(p.activity?.environment??p.activity_environment);const history=await readActivityAudit('sase',env,body.project_id);const base=history.at(-1)?.activity??p.activity??{...createActivity({},'unknown'),environment:env};return Response.json(await correctActivity('sase',env,body.project_id,base,body.expected_version,body,actor.email),{headers});}catch{return Response.json({error:'Invalid correction or version conflict; reload and check the evidence reference'},{status:409,headers});}}
