'use client';
import type {BriefFields} from '@/lib/buying-workspace-project';
import {quickListingReadiness} from '@/lib/publication-policy';
import {SECTOR_LABELS,REGION_LABELS} from '@/lib/shortlist-core';
export default function PublicationPreview({fields,onReview}:{fields:Partial<BriefFields>;onReview?:()=>void}){
 const rows:[string,string][]=[['Solution',fields.scope?.toUpperCase()||'Choose SASE, SD-WAN or SSE'],['Sector',SECTOR_LABELS[fields.sector as keyof typeof SECTOR_LABELS]||'Choose your sector'],['Sites',fields.sites||'Add your site count'],['Regions',fields.regions?.map(r=>REGION_LABELS[r as keyof typeof REGION_LABELS]||r).join(', ')||'Add your regions'],['Timescale',fields.timescale||'Add your buying timescale']];
 const readiness=quickListingReadiness({solutionScope:fields.scope??'',sector:fields.sector??'',siteCount:Number(fields.sites),regions:fields.regions??[],timescale:fields.timescale??'',outcome:fields.outcome??'',operatingModel:fields.operatingModel??'any'});
 const missing=readiness.reasons;
 const hasProjectDetails=[fields.sector,fields.sites,fields.timescale,fields.outcome].some(value=>Boolean(value?.trim()));
 return <section className="nf-notice-preview" aria-label="Opportunity Board notice preview"><span>Your Opportunity Board notice</span><p className="nf-notice-privacy"><strong>Suppliers see:</strong> the scope, sector, sites, regions, timescale and requirement you approve. <strong>Private:</strong> your company, work email and pricing. Leave identifying details out of the public requirement.</p><h2>{fields.sector?`${SECTOR_LABELS[fields.sector as keyof typeof SECTOR_LABELS]||fields.sector} project`:'Your project, ready to describe.'}</h2><p>{fields.outcome||'Describe the change your business needs. You can publish a basic statement of requirements, a Short RFP, a Detailed RFP or your own RFP / RFI.'}</p><dl>{rows.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><div className="nf-notice-next"><strong>{missing.length?'Before you review':'Your project is ready for review'}</strong><p>{missing.length?`Add the remaining brief details before review. A full RFP is optional.`:'You can add more RFP detail later. Check your notice and verify your work email before publishing.'}</p></div>{onReview && hasProjectDetails && <button type="button" onClick={onReview}>{readiness.allowed?"Review my opportunity":"Complete my project brief"} <span aria-hidden="true">→</span></button>}<small>Your company and work email stay private. You approve the public wording before anything is published.</small><a href="/sase/opportunities/board/">See the Opportunity Board ↗</a></section>;
}
